---
edit_uri: edit/main/docs/
# yamllint disable-line rule:line-length
copyright: "Where Trust Meets Innovation"
site_author: Punta Cana, Dominican Republic - August 2024

extra:
  homepage: https://amerintlxperts2024.github.io/.github/
  generator: false
  social:
    - icon: custom/fc-lib-facebook
      link: https://www.facebook.com/Fortinet/
    - icon: custom/fc-lib-twitter
      link: https://x.com/Fortinet
    - icon: custom/fc-lib-youtube
      link: https://www.youtube.com/channel/UCJHo4AuVomwMRzgkA5DQEOA
    - icon: custom/fc-lib-linkedin
      link: https://www.linkedin.com/company/fortinet/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material
  custom_dir: docs/theme/
  logo: theme/logo.svg
  favicon: theme/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: Roboto Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # yamllint disable-line
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # yamllint disable-line
      options:
        custom_icons:
          - docs/theme/.icons
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # yamllint disable-line
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - awesome-pages
  - search
  - with-pdf:
      output_path: ./docs/document.pdf
