---
site_name: Americas International Xperts 2024
site_description: Fortinet Subject Matter Experts Conference
site_url: https://amerintlxperts2024.github.io/.github/
site_author: Punta Cana, Dominican Republic - August 2024
repo_name: "amerintlxperts2024/.github"
repo_url: https://github.com/amerintlxperts2024/.github/
edit_uri: edit/main/docs/
INHERIT: theme/mkdocs.yml
