---
# edit_uri: edit/main/
# yamllint disable-line rule:line-length
copyright: "Fortinet, Inc."
site_author: "Docs Team"
site_name: "Hands on Labs"

extra:
  homepage: https://docs.amerintlxperts.com
  generator: true
  social:
    - icon: custom/fc-lib-facebook
      link: https://www.facebook.com/Fortinet/
    - icon: custom/fc-lib-twitter
      link: https://x.com/Fortinet
    - icon: custom/fc-lib-youtube
      link: https://www.youtube.com/channel/UCJHo4AuVomwMRzgkA5DQEOA
    - icon: custom/fc-lib-linkedin
      link: https://www.linkedin.com/company/fortinet/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - theme/extra.css

use_directory_urls: false
theme:
  name: material
  custom_dir: docs/theme
  logo: theme/XpertsSummitBanner.png
  logo_dark: theme/XpertsSummitBanner-dark.png
  favicon: theme/favicon.ico
  # icon:
  #   repo: fontawesome/brands/github
  font:
    text: Inter
    code: Roboto Mono
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # yamllint disable-line
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # yamllint disable-line
      options:
        custom_icons:
          - docs/theme/.icons
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # yamllint disable-line
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - exclude:
      glob:
        - "README.md"
  - awesome-pages
  - search
  - gh-admonitions
  # - chat:
  #    docs_chat_endpoint: "https://ollama.robinmordasiewicz.amerintlxperts.com/api/chat"
  - literate-nav:
      nav_file: SUMMARY.md
#  - git-revision-date-localized:
#      enable_creation_date: false
#  - with-pdf:
#      output_path: document.pdf

not_in_nav: |
  index.md
