---
# yamllint disable-line rule:line-length
copyright: "Where Trust Meets Innovation"

extra:
  homepage: https://amerintlxperts2024.github.io/.github/
  annotate:
    json: [.s2]
  generator: false
  social:
    - icon: custom/fc-lib-facebook
      link: https://www.facebook.com/Fortinet/
    - icon: custom/fc-lib-twitter
      link: https://x.com/Fortinet
    - icon: custom/fc-lib-youtube
      link: https://www.youtube.com/channel/UCJHo4AuVomwMRzgkA5DQEOA
    - icon: custom/fc-lib-linkedin
      link: https://www.linkedin.com/company/fortinet/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css: [theme/extra.css]
# extra_javascript: [extra.js]

theme:
  name: material
  include_sidebar: false
  custom_dir: docs/theme/
  logo: theme/logo.svg
  favicon: theme/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - announce.dismiss
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.footer
    # - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: fortinet
      accent: fortinet
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: fortinet
      accent: fortinet
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Inter
    code: Roboto Mono

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # yamllint disable-line
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # yamllint disable-line
      options:
        custom_icons:
          - theme/overrides/.icons
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      toc_depth: "1-1"
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # yamllint disable-line
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: amerintlxperts2024
      repo: docs-template
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - glightbox
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - awesome-pages
  - minify:
      minify_html: true
