---
name: build docs

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**.md"

jobs:
  terraform:
    name: "Trigger Build"
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: amerintlxperts/.github
          event-type: docs
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
